# Generated by Django 2.2.2 on 2023-11-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('preferred_pet_category', models.CharField(choices=[('DOG', 'DOG'), ('CAT', 'CAT'), ('PARROT', 'PARROT'), ('RABBIT', 'RABBIT'), ('OTHERS', 'OTHERS')], default=None, max_length=20, null=True)),
                ('preferred_pet_size', models.CharField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default=None, max_length=20, null=True)),
                ('preferred_pet_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('category', models.CharField(choices=[('DOG', 'DOG'), ('CAT', 'CAT'), ('PARROT', 'PARROT'), ('RABBIT', 'RABBIT'), ('OTHERS', 'OTHERS')], default=None, max_length=20, null=True)),
                ('size', models.CharField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default=None, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=None, max_length=20, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ADOPTED', 'ADOPTED')], default=None, max_length=20, null=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_core.Adopter')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_core.Shelter')),
            ],
        ),
    ]
