# Generated by Django 2.2.1 on 2023-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
