# Generated by Django 2.2.2 on 2023-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0002_auto_20231120_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
