# Generated by Django 2.2.1 on 2023-11-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0002_auto_20231127_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
