# Generated by Django 2.2.2 on 2023-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0003_pet_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='shelter_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
