# Generated by Django 2.2.1 on 2023-12-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0004_auto_20231201_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
