# Generated by Django 2.2.2 on 2023-11-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0004_shelter_shelter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_core.Adopter'),
        ),
    ]
