# Generated by Django 2.2.2 on 2023-12-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0005_auto_20231201_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='size',
            new_name='pet_size',
        ),
    ]
