# Generated by Django 2.2.2 on 2023-11-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0006_auto_20231123_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_core.Adopter'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_core.Shelter'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'AVAILABLE'), ('ADOPTED', 'ADOPTED')], max_length=20, null=True),
        ),
    ]
