# Generated by Django 2.2.2 on 2023-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_core', '0007_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
